export const TopCollegesData = [
  {
    name: "BVRIT Hyderabad College of Engineering",
    location: "Hyderabad, Telangana",
    nirf_ranking: 21,
    naac_grade: "Not Mentioned",
    highest_package: "12 LPA - 30 LPA",
    avg_package: "12 LPA",
    fee_structure: "₹2,30,700 (1st Year Fees)",
    courses_offered: "10 June - 18 Jun 2024",
    logo_url: "https://bvrit.ac.in/wp-content/uploads/2021/09/cropped-bvrit-logo.png",
  },
  {
    name: "BVRIT Hyderabad College of Engineering",
    location: "Hyderabad, Telangana",
    nirf_ranking: 21,
    naac_grade: "Not Mentioned",
    highest_package: "12 LPA - 30 LPA",

    fee_structure: "₹2,30,700 (1st Year Fees)",
    courses_offered: "10 June - 18 Jun 2024",
    logo_url: "https://bvrit.ac.in/wp-content/uploads/2021/09/cropped-bvrit-logo.png",
  },
  {
    name: "BVRIT Hyderabad College of Engineering",
    location: "Hyderabad, Telangana",
    nirf_ranking: 21,
    naac_grade: "Not Mentioned",
    highest_package: "12 LPA - 30 LPA",
    avg_package: "12 LPA",
    fee_structure: "₹2,30,700 (1st Year Fees)",
    courses_offered: "10 June - 18 Jun 2024",
    logo_url: "https://bvrit.ac.in/wp-content/uploads/2021/09/cropped-bvrit-logo.png",
  },
  {
    name: "BVRIT Hyderabad College of Engineering",
    location: "Hyderabad, Telangana",
    nirf_ranking: 21,
    naac_grade: "Not Mentioned",
    highest_package: "12 LPA - 30 LPA",
    avg_package: "12 LPA",
    fee_structure: "₹2,30,700 (1st Year Fees)",
    courses_offered: "10 June - 18 Jun 2024",
    logo_url: "https://bvrit.ac.in/wp-content/uploads/2021/09/cropped-bvrit-logo.png",
  },
  {
    name: "BVRIT Hyderabad College of Engineering",
    location: "Hyderabad, Telangana",
    nirf_ranking: 21,
    naac_grade: "Not Mentioned",
    highest_package: "12 LPA - 30 LPA",
    avg_package: "12 LPA",
    fee_structure: "₹2,30,700 (1st Year Fees)",
    courses_offered: "10 June - 18 Jun 2024",
    logo_url: "https://bvrit.ac.in/wp-content/uploads/2021/09/cropped-bvrit-logo.png",
  },
  {
    name: "BVRIT Hyderabad College of Engineering",
    location: "Hyderabad, Telangana",
    nirf_ranking: 21,
    naac_grade: "Not Mentioned",
    highest_package: "12 LPA - 30 LPA",
    avg_package: "12 LPA",
    fee_structure: "₹2,30,700 (1st Year Fees)",
    courses_offered: "10 June - 18 Jun 2024",
    logo_url: "https://bvrit.ac.in/wp-content/uploads/2021/09/cropped-bvrit-logo.png",
  },
  {
    name: "BVRIT Hyderabad College of Engineering",
    location: "Hyderabad, Telangana",
    nirf_ranking: 21,
    naac_grade: "Not Mentioned",
    highest_package: "12 LPA - 30 LPA",
    avg_package: "12 LPA",
    fee_structure: "₹2,30,700 (1st Year Fees)",
    courses_offered: "10 June - 18 Jun 2024",
    logo_url: "https://bvrit.ac.in/wp-content/uploads/2021/09/cropped-bvrit-logo.png",
  },
  {
    name: "BVRIT Hyderabad College of Engineering",
    location: "Hyderabad, Telangana",
    nirf_ranking: 21,
    naac_grade: "Not Mentioned",
    highest_package: "12 LPA - 30 LPA",
    avg_package: "12 LPA",
    fee_structure: "₹2,30,700 (1st Year Fees)",
    courses_offered: "10 June - 18 Jun 2024",
    logo_url: "https://bvrit.ac.in/wp-content/uploads/2021/09/cropped-bvrit-logo.png",
  },
  {
    name: "BVRIT Hyderabad College of Engineering",
    location: "Hyderabad, Telangana",
    nirf_ranking: 21,
    naac_grade: "Not Mentioned",
    highest_package: "12 LPA - 30 LPA",
    avg_package: "12 LPA",
    fee_structure: "₹2,30,700 (1st Year Fees)",
    courses_offered: "10 June - 18 Jun 2024",
    logo_url: "https://bvrit.ac.in/wp-content/uploads/2021/09/cropped-bvrit-logo.png",
  },
  {
    name: "BVRIT Hyderabad College of Engineering",
    location: "Hyderabad, Telangana",
    nirf_ranking: 21,
    naac_grade: "Not Mentioned",
    highest_package: "12 LPA - 30 LPA",
    avg_package: "12 LPA",
    fee_structure: "₹2,30,700 (1st Year Fees)",
    courses_offered: "10 June - 18 Jun 2024",
    logo_url: "https://bvrit.ac.in/wp-content/uploads/2021/09/cropped-bvrit-logo.png",
  },
];
